import peopleIcon from "../images/people.png";

export const JobOpeningData = [
    {
        id: 1,
        title: "2025 한미약품 고형제 생산파트 신입/경력채용",
        company: "한미약품",
        location: "경기 화성",
        type: "생산·제조",
        status: "승인완료",
        statusColor: "#1B960D",
        createdAt: "2025.07.11",
        createdBy: "김병호",
        people: 14,
        icon: peopleIcon,
    },
    {
        id: 2,
        title: "창문형 에어컨 설치기사  및 보조기사 채용",
        company: "창문형 에어컨",
        location: "인천 서구",
        type: "시설·정비",
        status: "승인대기",
        statusColor: "#0D2B96",
        createdAt: "2025.07.03",
        createdBy: "김형석",
        people: "비공개",
    },
    {
        id: 3,
        title: "냉동 탑차 운행기사 구합니다. ",
        company: "냉동 탑차",
        location: "경기도 구리시",
        type: "운송·물류",
        status: "승인취소",
        statusColor: "#E03607",
        createdAt: "2025.06.28",
        createdBy: "유상오",
        people: 3,
        icon: peopleIcon,
    },
    {
        id: 4,
        title: "냉동 탑차 운행기사 구합니다. ",
        company: "냉동 탑차",
        location: "경기도 구리시",
        type: "운송·물류",
        status: "승인취소",
        statusColor: "#E03607",
        createdAt: "2025.06.28",
        createdBy: "유상오",
        people: 3,
        icon: peopleIcon,
    },
    {
        id: 5,
        title: "냉동 탑차 운행기사 구합니다. ",
        company: "냉동 탑차",
        location: "경기도 구리시",
        type: "운송·물류",
        status: "승인취소",
        statusColor: "#E03607",
        createdAt: "2025.06.28",
        createdBy: "유상오",
        people: 3,
        icon: peopleIcon,
    },
    {
        id: 6,
        title: "냉동 탑차 운행기사 구합니다. ",
        company: "냉동 탑차",
        location: "경기도 구리시",
        type: "운송·물류",
        status: "승인취소",
        statusColor: "#E03607",
        createdAt: "2025.06.28",
        createdBy: "유상오",
        people: 3,
        icon: peopleIcon,
    },
    {
        id: 7,
        title: "냉동 탑차 운행기사 구합니다. ",
        company: "냉동 탑차",
        location: "경기도 구리시",
        type: "운송·물류",
        status: "승인취소",
        statusColor: "#E03607",
        createdAt: "2025.06.28",
        createdBy: "유상오",
        people: 3,
        icon: peopleIcon,
    },
    {
        id: 8,
        title: "냉동 탑차 운행기사 구합니다. ",
        company: "냉동 탑차",
        location: "경기도 구리시",
        type: "운송·물류",
        status: "승인취소",
        statusColor: "#E03607",
        createdAt: "2025.06.28",
        createdBy: "유상오",
        people: 3,
        icon: peopleIcon,
    },
    {
        id: 9,
        title: "냉동 탑차 운행기사 구합니다. ",
        company: "냉동 탑차",
        location: "경기도 구리시",
        type: "운송·물류",
        status: "승인취소",
        statusColor: "#E03607",
        createdAt: "2025.06.28",
        createdBy: "유상오",
        people: 3,
        icon: peopleIcon,
    },
    {
            id: 10,
        title: "냉동 탑차 운행기사 구합니다. ",
        company: "냉동 탑차",
        location: "경기도 구리시",
        type: "운송·물류",
        status: "승인취소",
        statusColor: "#E03607",
        createdAt: "2025.06.28",
        createdBy: "유상오",
        people: 3,
        icon: peopleIcon,
    },
    {
        id: 11,
        title: "냉동 탑차 운행기사 구합니다. ",
        company: "냉동 탑차",
        location: "경기도 구리시",
        type: "운송·물류",
        status: "승인취소",
        statusColor: "#E03607",
        createdAt: "2025.06.28",
        createdBy: "유상오",
        people: 3,
        icon: peopleIcon,
    },

]